---
- name: Set up SSH access for a new host
  hosts: "{{ target_host }}"
  become: yes  # Use sudo to ensure we can write to the system files
  gather_facts: no
  vars:
    ansible_user: tcarter  # Define the username as a variable

  tasks:
    - name: Ensure .ssh directory exists with correct permissions
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}" # Or the primary group of ansible_user

    - name: Add SSH public key to authorized_keys
      ansible.posix.authorized_key:
        path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', '/Users/terrycarter/.ssh/id_ed25519.pub') }}"
        state: present
        # manage_dir: yes # Default is yes, ensures .ssh exists with 0700

    - name: Ensure the authorized_keys file has the correct permissions
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}" # Or the primary group of ansible_user
        mode: '0600'

# -----------------------------------------------------
# Note: Before running this playbook, SSH into the machine once to store the host key:
# ssh tcarter@<TARGET_NAME>
#
# This ensures the target machine is recognized and avoids SSH connection errors.
#
# To execute this playbook, run the following command:
# ansible-playbook playbooks/ssh_setup.yml --extra-vars "target_host=<TARGET_NAME>" --ask-pass --ask-become-pass
#
# Replace <TARGET_NAME> with the full name of the machine you want to set up.
# Example:
# ansible-playbook playbooks/ssh_setup.yml --extra-vars "target_host=pi0-4.attlocal.net" --ask-pass --ask-become-pass
#
# After running the playbook and confirming success, remember to add the new hostname
# (e.g., pi0-4.attlocal.net) to your `hosts.ini` file (if not already there or correctly patterned)
# so you can easily target it in future Ansible runs.
#
# Example: Add a new entry for the target host:
# [new_hosts]
# pi0-4.attlocal.net
#
# This will allow you to manage the host without needing to specify the IP manually each time.

